CREATE TABLE public.pais (
                             id_pais bigserial NOT NULL,
                             created_at timestamp NULL,
                             nombre_pais varchar(20) NULL,
                             updated_at timestamp NULL,
                             CONSTRAINT pais_pkey PRIMARY KEY (id_pais)
);

INSERT INTO pais (nombre_pais) VALUES
                                          ('Afganistán'),
                                          ('Albania'),
                                          ('Alemania'),
                                          ('Andorra'),
                                          ('Angola'),
                                          ('Antigua y Barbuda'),
                                          ('Arabia Saudita'),
                                          ('Argelia'),
                                          ('Argentina'),
                                          ('Armenia'),
                                          ('Australia'),
                                          ('Austria'),
                                          ('Azerbaiyán'),
                                          ('Bahamas'),
                                          ('Bahréin'),
                                          ('Bangladés'),
                                          ('Barbados'),
                                          ('Bielorrusia'),
                                          ('Bélgica'),
                                          ('Belice'),
                                          ('Benín'),
                                          ('Bolivia'),
                                          ('Bosnia y Herzegovina'),
                                          ('Botsuana'),
                                          ('Brasil'),
                                          ('Brunéi'),
                                          ('Bulgaria'),
                                          ('Burkina Faso'),
                                          ('Burundi'),
                                          ('Bután'),
                                          ('Cabo Verde'),
                                          ('Camboya'),
                                          ('Camerún'),
                                          ('Canadá'),
                                          ('Catar'),
                                          ('Chad'),
                                          ('Chile'),
                                          ('China'),
                                          ('Chipre'),
                                          ('Colombia'),
                                          ('Comoras'),
                                          ('Congo'),
                                          ('Corea del Norte'),
                                          ('Corea del Sur'),
                                          ('Costa de Marfil'),
                                          ('Costa Rica'),
                                          ('Croacia'),
                                          ('Cuba'),
                                          ('Dinamarca'),
                                          ('Dominica'),
                                          ('Ecuador'),
                                          ('Egipto'),
                                          ('El Salvador'),
                                          ('Emiratos Árabes Unidos'),
                                          ('Eritrea'),
                                          ('Eslovaquia'),
                                          ('Eslovenia'),
                                          ('España'),
                                          ('Estados Unidos'),
                                          ('Estonia'),
                                          ('Eswatini'),
                                          ('Etiopía'),
                                          ('Fiyi'),
                                          ('Filipinas'),
                                          ('Finlandia'),
                                          ('Francia'),
                                          ('Gabón'),
                                          ('Gambia'),
                                          ('Georgia'),
                                          ('Ghana'),
                                          ('Granada'),
                                          ('Grecia'),
                                          ('Guatemala'),
                                          ('Guinea'),
                                          ('Guinea-Bisáu'),
                                          ('Guinea Ecuatorial'),
                                          ('Guyana'),
                                          ('Haití'),
                                          ('Honduras'),
                                          ('Hungría'),
                                          ('India'),
                                          ('Indonesia'),
                                          ('Irak'),
                                          ('Irán'),
                                          ('Irlanda'),
                                          ('Islandia'),
                                          ('Islas Marshall'),
                                          ('Islas Salomón'),
                                          ('Israel'),
                                          ('Italia'),
                                          ('Jamaica'),
                                          ('Japón'),
                                          ('Jordania'),
                                          ('Kazajistán'),
                                          ('Kenia'),
                                          ('Kirguistán'),
                                          ('Kiribati'),
                                          ('Kuwait'),
                                          ('Laos'),
                                          ('Lesoto'),
                                          ('Letonia'),
                                          ('Líbano'),
                                          ('Liberia'),
                                          ('Libia'),
                                          ('Liechtenstein'),
                                          ('Lituania'),
                                          ('Luxemburgo'),
                                          ('Madagascar'),
                                          ('Malasia'),
                                          ('Malaui'),
                                          ('Maldivas'),
                                          ('Malí'),
                                          ('Malta'),
                                          ('Marruecos'),
                                          ('Mauricio'),
                                          ('Mauritania'),
                                          ('México'),
                                          ('Micronesia'),
                                          ('Moldavia'),
                                          ('Mónaco'),
                                          ('Mongolia'),
                                          ('Montenegro'),
                                          ('Mozambique'),
                                          ('Namibia'),
                                          ('Nauru'),
                                          ('Nepal'),
                                          ('Nicaragua'),
                                          ('Níger'),
                                          ('Nigeria'),
                                          ('Noruega'),
                                          ('Nueva Zelanda'),
                                          ('Omán'),
                                          ('Países Bajos'),
                                          ('Pakistán'),
                                          ('Palaos'),
                                          ('Panamá'),
                                          ('Papúa Nueva Guinea'),
                                          ('Paraguay'),
                                          ('Perú'),
                                          ('Polonia'),
                                          ('Portugal'),
                                          ('Reino Unido'),
                                          ('República Centroafricana'),
                                          ('República Checa'),
                                          ('República del Congo'),
                                          ('República Dominicana'),
                                          ('Ruanda'),
                                          ('Rumania'),
                                          ('Rusia'),
                                          ('Samoa'),
                                          ('San Cristóbal y Nieves'),
                                          ('San Marino'),
                                          ('San Vicente y las Granadinas'),
                                          ('Santa Lucía'),
                                          ('Santo Tomé y Príncipe'),
                                          ('Senegal'),
                                          ('Serbia'),
                                          ('Seychelles'),
                                          ('Sierra Leona'),
                                          ('Singapur'),
                                          ('Siria'),
                                          ('Somalia'),
                                          ('Sri Lanka'),
                                          ('Sudáfrica'),
                                          ('Sudán'),
                                          ('Sudán del Sur'),
                                          ('Suecia'),
                                          ('Suiza'),
                                          ('Surinam'),
                                          ('Tailandia'),
                                          ('Tanzania'),
                                          ('Tayikistán'),
                                          ('Timor Oriental'),
                                          ('Togo'),
                                          ('Tonga'),
                                          ('Trinidad y Tobago'),
                                          ('Túnez'),
                                          ('Turkmenistán'),
                                          ('Turquía'),
                                          ('Tuvalu'),
                                          ('Ucrania'),
                                          ('Uganda'),
                                          ('Uruguay'),
                                          ('Uzbekistán'),
                                          ('Vanuatu'),
                                          ('Vaticano'),
                                          ('Venezuela'),
                                          ('Vietnam'),
                                          ('Yemen'),
                                          ('Yibuti'),
                                          ('Zambia'),
                                          ('Zimbabue');
